name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: laravel/laravel
          path: laravel
          run: |
            composer install
            php artisan key:generate
            
            
      

  
  


