name: PHP Composer

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Plugin
        uses: actions/checkout@v2
        with:
          repository: 'bueno-networks/laravel-plugin-core'
          path: ./plugin
        
      - name: Clone Laravel
        uses: actions/checkout@v2
        with:
          repository: 'laravel/laravel'
          path: ./laravel
          
      - name: Setup Plugin
        run: | 
          cd plugin 
          npm install
          composer install
          
      - name: Setup Laravel
        run: | 
          cd laravel 
          cp .env.example .env
          composer install
          php artisan key:generate
          composer config repositories.plugin path ../plugin  
          cat composer.json
          composer require bnw/laravel-plugin-core
          
      - name: Run tests
        run: | 
          cd plugin
          composer test  
          
      - name: Listar Tudo
        run: ls -la ./ ; ls -la laravel; ls -la plugin
  
  
 
            
            
      

  
  


