name: PHP Composer

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Teste one line
      - run: composer create-project laravel/laravel
      - name: Listar
        run: ls -la
  
  
 
            
            
      

  
  


