name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
  
    steps:
  
      # Clona o Laravel
      - uses: actions/checkout@v2
        with:
          repository: laravel/laravel
          path: laravel
        
      # Setup
      - name: Configura o Laravel
        uses: ./laravel
        run: composer install
  
  


