name: PHP Composer

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Laravel    
        uses: actions/checkout@v2
        with:
          repository: 'bueno-networks/laravel-plugin-core'
          path: ./plugin
            
      - name: Clone Plugin
        uses: actions/checkout@v2
        with:
          repository: 'laravel/laravel'
          path: ./laravel
          
      - name: Setup Laravel
        run: | 
          cd laravel 
          php -r "file_exists('.env') || copy('.env.example', '.env')"
          composer install
          php artisan key:generate
          composer config repositories.plugin path ../plugin  
          composer require bnw/laravel-plugin-core
          
      - name: Setup Plugin
        run: | 
          cd plugin 
          composer install
          composer test  
          
      - name: Run tests
        run: | 
          cd plugin
          composer test  
          
      - name: Listar Tudo
        run: ls -la ./ ; ls -la laravel; ls -la plugin
  
  
 
            
            
      

  
  


