name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Instalação do projeto Laravel 
    - uses: actions/checkout@v2
      with:
        repository: laravel/laravel
        path: laravel
        
    - name: Dependencias do Laravel
      run: composer install
        
    # Instalação do plugin 
    - uses: actions/checkout@v2
      with:
        path: main

    - name: Pacotes NPM
      run: npm install

    - name: Validação do cComposer
      run: composer validate
      
    - name: Cache Composer
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Dependencias do Plugin
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Testes de Unidade
      run: composer test
